- hosts: master
  become: yes
  tasks:

    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"

    - name: Emptying hostname file of Group - Masters
      copy:
        content: ""
        dest: /etc/hostname

    - name: Change HOSTNAME of Group - Masters
      lineinfile:
        dest: /etc/hostname
        regexp: '.*{{ item }}$'
        line: "{{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.masters }}"
      register: reboot_req

    - name: Reboot immediately if there was a change in reboot_req.
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: reboot_req is changed

    - name: Wait for the reboot to complete if there was a change in reboot_req.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: reboot_req is changed

    - name: initialize the cluster
      shell: kubeadm init >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: kube
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    - name: install Pod network
      become: yes
      become_user: kube
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: download metrics-server and my repo
      become: yes
      become_user: kube
      shell: git clone https://github.com/kubernetes-incubator/metrics-server.git >> my_app.txt;
             git clone https://github.com/hiakki/kubernetes.git >> my_app.txt
      args:
        chdir: $HOME
        creates: my_app.txt

    - name: updating metrics-server-deployment.yaml
      copy:
        src: /home/kube/kubernetes/metrics-server-deployment.yaml
        dest: /home/kube/metrics-server/deploy/1.8+/
        remote_src: yes
        owner: kube

    - name: Deploying Metrics-Server for HPA
      become: yes
      become_user: kube
      shell: kubectl apply -f metrics-server/deploy/1.8+/ >> metrics_server.txt
      args:
        chdir: $HOME
        creates: metrics_server.txt

